#@package _global_
project_root: "/Users/postbg/IdeaProjects/DataStructureAssignment/Assignment1"
num_assignment: 1
assigment_examples_root: "/Users/postbg/PycharmProjects/AutoJudge.python/assigment1"