#@package _global_
submissions_root: "/Users/postbg/DataStructures/A5/Assignment5"
num_problems: 1
result_path: "/Users/postbg/DataStructures/A5/result"
test_cases_code: simple_file
assigment_testcase_root: "/Users/postbg/DataStructures/A5/Testcase"
output_path: "/Users/postbg/DataStructures/A5/outputs"