#@package _global_
assignment_root_name: "Assignment1"
submissions_root: "/Users/postbg/Downloads/Assignment0_"
num_problems: 1
result_path: "/Users/postbg/Downloads/Assignment0_/result.csv"
test_cases_code: assignment0_manual