#@package _global_
submissions_root: "/Users/postbg/DataStructures/A4/Assignment4"
num_problems: 1
result_path: "/Users/postbg/DataStructures/A4/result"
test_cases_code: simple_file
assigment_testcase_root: "/Users/postbg/DataStructures/A4/Testcase"
output_path: "/Users/postbg/DataStructures/A4/outputs"