#@package _global_
assignment_root_name: "Assignment0"
submissions_root: "/Users/postbg/Downloads/DS"
num_problems: 1
test_cases_code: assignment0_manual
result_path: "/Users/postbg/Downloads/DS/result.csv"