#@package _global_
submissions_root: "/Users/postbg/DataStructures/A3/Assignment3"
num_problems: 1
result_path: "/Users/postbg/DataStructures/A3/result"
test_cases_code: assignment3_manual
output_path: "/Users/postbg/DataStructures/A3/outputs"